BEGIN
  -- Granting INSERT,UPDATE,DELETE privilege on the "TRAINING_VIEW" to COACHES,MANAGERS
 
  EXECUTE IMMEDIATE 'GRANT INSERT,UPDATE,DELETE ON TRAINING_VIEW TO COACHES,MANAGERS';
  DBMS_OUTPUT.PUT_LINE('Write access granted successfully.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Write permission given');
END;
/
 
BEGIN
  -- Grant INSERT,UPDATE,DELETE privilege on the "PLAYER_HEALTH_RECORD_VIEW" to MEDICALSTAFFS
  EXECUTE IMMEDIATE 'GRANT INSERT,UPDATE,DELETE ON PLAYER_HEALTH_RECORD_VIEW TO MEDICALSTAFFS';
  DBMS_OUTPUT.PUT_LINE('Write access granted successfully.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Write permission given');
END;
/
BEGIN
  -- Grant INSERT,UPDATE,DELETE privilege on the "TEAM_PLAYER_SCHEDULE_VIEW" to MANAGERS
  EXECUTE IMMEDIATE 'GRANT INSERT,UPDATE,DELETE ON TEAM_PLAYER_SCHEDULE_VIEW TO MANAGERS';
  DBMS_OUTPUT.PUT_LINE('Write access granted successfully.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Write permission given');
END;
/
 
BEGIN
  -- Grant INSERT,UPDATE,DELETE privilege on the "SPONSORSHIPS_SPORTS_TEAM_VIEW" to MANAGERS
  EXECUTE IMMEDIATE 'GRANT INSERT,UPDATE,DELETE ON SPONSORSHIPS_SPORTS_TEAM_VIEW TO MANAGERS';
  DBMS_OUTPUT.PUT_LINE('Write access granted successfully.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Write permission given');
END;
/